tango_with_django_project/rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('category/<slug:category_name_slug>/', views.ShowCategoryView.as_view(), name='show_category'),
    path('category/<slug:category_name_slug>/add_page/', views.AddPageView.as_view(), name='add_page'),
    path('add_category/', views.AddCategoryView.as_view(), name='add_category'),
    # path('register/', views.register, name='register'),
    # path('login/', views.user_login, name='login'),
    # path('logout/', views.user_logout, name='logout'),
    path('restricted/', views.RestrictedView.as_view(), name='restricted'),
    # path('search/', views.search, name='search'),
    path('goto/', views.GotoView.as_view(), name='goto'),
    path('register_profile/', views.RegisterProfileView.as_view(), name='register_profile'),
    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),
    path('profiles/', views.ListProfilesView.as_view(), name='list_profiles'),
    path('like_category/', views.LikeCategoryView.as_view(), name='like_category'),
    path('suggest/', views.CategorySuggestionView.as_view(), name='suggest'),
    path('search_add_page/', views.SearchAddPageView.as_view(), name='search_add_page'),
]

tango_with_django_project/tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse
from registration.backends.simple.views import RegistrationView
from rango import views


class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('rango:register_profile')


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
    path('accounts/register/', MyRegistrationView.as_view(), name='registration_register'),
    path('accounts/',include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tango_with_django_project/rango/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone


class Category(models.Model):
    NAME_MAX_LENGTH = 128

    name = models.CharField(max_length=NAME_MAX_LENGTH, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        if self.views <= 0:
            self.views = 0

        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Page(models.Model):
    TITLE_MAX_LENGTH = 128
    URL_MAX_LENGTH = 200

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    url = models.URLField()
    views = models.IntegerField(default=0)
    last_visit = models.DateTimeField(blank=True)

    def save(self, *args, **kwargs):
        self.last_visit = timezone.now()
        super(Page, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    # Эта строка обязательна. Связывает UserProfile с экземпляром модели User.
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Дополнительные атрибуты, которые мы хотим включить.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

tango_with_django_project/rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import Page, Category, UserProfile


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,
                           help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # Встроенный класс для предоставления дополнительной информации о форме.
    class Meta:
        # Обеспечьте связь между ModelForm и моделью
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                            help_text='Please enter the title of the page.')
    url = forms.URLField(max_length=200,
                         help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        # Обеспечьте связь между ModelForm и моделью
        model = Page

        # Какие поля мы хотим включить в нашу форму?
        # Таким образом, нам не нужны все поля в модели.
        # Некоторые поля могут допускать значения NULL; мы можем не захотеть их включать.
        # Здесь мы скрываем внешний ключ.
        # мы можем либо исключить поле категории из формы,
        exclude = ('category',)
        # или укажите поля для включения (не включайте поле категории).
        # fields = ('title', 'url', 'views')

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        # Если url не пустой и не начинается с "http://",
        # тогда добавьте "http://".
        if url and not url.startswith("http://"):
            url = f"http://{url}"
            cleaned_data['url'] = url
        return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture',)

tango_with_django_project/rango/views.py
from datetime import datetime
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.utils import timezone
from django.views import View
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator

from rango.bing_search import run_query
from rango.models import Category, Page, UserProfile
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm


class IndexView(View):
    def get(self, request):
        # Запросить в базе данных список ВСЕХ категорий, хранящихся в настоящее время.
        # Упорядочить категории по количеству лайков в порядке убывания.
        # Получить только первые 5 - или все, если меньше 5.
        # Поместите список в наш словарь context_dict (выделив жирным шрифтом!),
        # Который будет передан в механизм шаблонов.
        category_list = Category.objects.order_by('-likes')[:5]
        page_list = Page.objects.order_by('-views')[:5]

        context_dict = {}
        context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
        context_dict['categories'] = category_list
        context_dict['pages'] = page_list

        # context_dict['visits'] = request.session['visits']

        # Вызвать вспомогательную функцию для обработки файлов cookie
        visitor_cookie_handler(request)

        # # Получите наш объект Response заранее, чтобы мы могли добавить информацию о cookie.
        # response = render(request, 'rango/index.html', context=context_dict)
        # # Вернуть ответ пользователю, обновив все файлы cookie, которые необходимо изменить.
        # return response

        return render(request, 'rango/index.html', context=context_dict)


class AboutView(View):
    def get(self, request):
        context_dict = {}

        visitor_cookie_handler(request)
        context_dict['visits'] = request.session['visits']

        return render(request, 'rango/about.html', context_dict)


class ShowCategoryView(View):
    def create_context_dict(self, category_name_slug):
        # Создать контекстный словарь, который мы можем передать
        # механизму рендеринга шаблонов.
        context_dict = {}

        try:
            # Можем ли мы найти ярлык с названием категории с заданным именем?
            # Если мы не можем, метод .get () вызывает исключение DoesNotExist.
            # Метод .get () возвращает один экземпляр модели или вызывает исключение.
            category = Category.objects.get(slug=category_name_slug)
            # Получить все связанные страницы.
            # Filter () вернет список объектов страницы или пустой список.
            pages = Page.objects.filter(category=category).order_by('-views')

            # Добавляет наш список результатов в контекст шаблона под страницами имен.
            context_dict['pages'] = pages
            # Мы также добавляем объект категории из
            # базы данных в контекстный словарь.
            # Мы будем использовать это в шаблоне, чтобы убедиться, что категория существует.
            context_dict['category'] = category
        except Category.DoesNotExist:
            # Мы попадаем сюда, если не нашли указанную категорию.
            # Ничего не делайте -
            # шаблон отобразит для нас сообщение "без категории".
            context_dict['pages'] = None
            context_dict['category'] = None

        return context_dict

    def get(self, request, category_name_slug):
        context_dict = self.create_context_dict(category_name_slug)
        return render(request, 'rango/category.html', context_dict)

    @method_decorator(login_required)
    def post(self, request, category_name_slug):
        context_dict = self.create_context_dict(category_name_slug)
        query = request.POST['query'].strip()

        if query:
            context_dict['result_list'] = run_query(query)
            context_dict['query'] = query

        # Выполните рендеринг ответа и верните его клиенту.
        return render(request, 'rango/category.html', context_dict)


class AddCategoryView(View):
    @method_decorator(login_required)
    def get(self, request):
        form = CategoryForm()
        return render(request, 'rango/add_category.html', {'form': form})

    @method_decorator(login_required)
    def post(self, request):
        form = CategoryForm(request.POST)

        # Нам предоставили действующую форму?
        if form.is_valid():
            # Сохраните новую категорию в базе данных.
            form.save(commit=True)
            # Теперь, когда категория сохранена, мы можем это подтвердить.
            # На данный момент просто перенаправьте пользователя обратно в представление индекса.
            return redirect(reverse('rango:index'))
        else:
            # Предоставленная форма содержала ошибки -
            # просто распечатайте их в терминал.
            print(form.errors)

        # Будет обрабатывать случаи неправильной формы, новой формы или отсутствия формы.
        # Визуализировать форму с сообщениями об ошибках (если есть).
        return render(request, 'rango/add_category.html', {'form': form})


class AddPageView(View):
    def get_category_name(self, category_name_slug):
        try:
            category = Category.objects.get(slug=category_name_slug)
        except Category.DoesNotExist:
            category = None

        return category

    @method_decorator(login_required)
    def get(self, request, category_name_slug):
        form = PageForm()
        category = self.get_category_name(category_name_slug)

        if category is None:
            return redirect(reverse('rango:index'))

        context_dict = {'form': form, 'category': category}
        return render(request, 'rango/add_page.html', context_dict)

    @method_decorator(login_required)
    def post(self, request, category_name_slug):
        form = PageForm(request.POST)
        category = self.get_category_name(category_name_slug)

        # Вы не можете добавить страницу в категорию, которая не существует ...
        if category is None:
            return redirect(reverse('rango:index'))

        if form.is_valid():
            page = form.save(commit=False)
            page.category = category
            page.views = 0
            page.save()

            return redirect(reverse('rango:show_category', kwargs={'category_name_slug': category_name_slug}))
        else:
            print(form.errors)

        context_dict = {'form': form, 'category': category}
        return render(request, 'rango/add_page.html', context=context_dict)


class RestrictedView(View):
    @method_decorator(login_required)
    def get(self, request):
        return render(request, 'rango/restricted.html')


class GotoView(View):
    def get(self, request):
        page_id = request.GET.get('page_id')

        try:
            selected_page = Page.objects.get(id=page_id)
        except Page.DoesNotExist:
            return redirect(reverse('rango:index'))

        selected_page.views = selected_page.views + 1
        selected_page.last_visit = timezone.now()
        selected_page.save()

        return redirect(selected_page.url)


class RegisterProfileView(View):
    @method_decorator(login_required)
    def get(self, request):
        form = UserProfileForm()
        context_dict = {'form': form}
        return render(request, 'rango/profile_registration.html', context_dict)

    @method_decorator(login_required)
    def post(self, request):
        form = UserProfileForm(request.POST, request.FILES)

        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()

            return redirect(reverse('rango:index'))
        else:
            print(form.errors)

        context_dict = {'form': form}
        return render(request, 'rango/profile_registration.html', context_dict)


class ProfileView(View):
    def get_user_details(self, username):
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            return None

        user_profile = UserProfile.objects.get_or_create(user=user)[0]
        form = UserProfileForm({'website': user_profile.website,
                                'picture': user_profile.picture})

        return(user, user_profile, form)

    @method_decorator(login_required)
    def get(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('rango:index'))

        contex_dict = {'user_profile': user_profile,
                       'selected_user': user,
                       'form': form}

        return render(request, 'rango/profile.html', contex_dict)

    @method_decorator(login_required)
    def post(self, requeset, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('rango:index'))

        form = UserProfileForm(requeset.POST, requeset.FILES, instance=user_profile)
        if form.is_valid():
            form.save(commit=True)
            return redirect('rango:profile', user.username)
        else:
            print(form.errors)

        context_dict = {'user_profile': user_profile,
                        'selected_user': user,
                        'form': form}
        return render(requeset, 'rango/profile.html', context_dict)


class ListProfilesView(View):
    @method_decorator(login_required)
    def get(self, request):
        profiles = UserProfile.objects.all()

        return render(request, 'rango/list_profiles.html', {'user_profile_list': profiles})


class LikeCategoryView(View):
    @method_decorator(login_required)
    def get(self, request):

tango_with_django_project/templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}About Rango{% endblock %}

{% block body_block %}

    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumbotron-heading">Rango says...</h1>
        </div>
    </div>
    <div>
        <h2 class="h2">
        here is the about page. <br />
        This tutorial has been put together by <strong>{{ my_name }}</strong>.<br />
        </h2>
    </div>

<!--JQuery JQuery JQuery JQuery JQuery JQuery JQuery JQuery-->
<br>
<button class="btn btn-primary"
        onclick="alert('You clicked the button using inline JavaScript.');">
    Нажми на меня - я использую обычный JavaScript!
</button>
<br>
<br>
<button class="btn btn-primary" id="about-btn">
    Нажмите на меня - я использую JQuery!
</button><br><br>
    <p>This is some text for the JQuery example.</p>
<br>
    <div id="msg">Привет! Я-еще один пример для тестирования JQuery.</div>
<br>
<!--00000000000000000000000000000000000000000000000000000000000000000000000000-->
    <div>
        <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
        <img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat" />
    </div>

<p>Visits: {{ visits }}</p>

{% endblock %}

tango_with_django_project/templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}Add a Category{% endblock %}

{% block body_block %}
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumbotron-heading">Add a Category</h1>
        </div>
    </div>


    <div class="container">
        <div class="row">
            <form role="form" id="category_form" method="post"
                  action="{% url 'rango:add_category' %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br />
                {{ field }}<br />
                <div class="p-2"></div>
            {% endfor %}
                <br />
                <button class="btn btn-primary" type="submit" name="submit">Create Category</button>
                <div class="p-5"></div>
            </form>
        </div>
    </div>
{% endblock %}

tango_with_django_project/templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title %}Add Page{% endblock %}

{% block body_block %}
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumbotron-heading">Add a Page to {{category.name}}</h1>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <form role="form" id="page_form" method="post"
                  action="{% url 'rango:add_page' category.slug %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br />
                {{ field }}<br />
                <div class="p-2"></div>
            {% endfor %}
                <br />
                <button class="btn btn-primary" type="submit" name="submit">
                    Add Page
                </button>
                <div class="p-5"></div>
            </form>
        </div>
    </div>
{% endblock %}

tango_with_django_project/templates/rango/base-old.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>
            Rango -
            {% block title_block %}
                How to Tango with Django!
            {% endblock %}
        </title>
    </head>
    <body>
        <div>
        {% block body_block %}
        {% endblock %}
        </div>
        <div>
            {% block sidebar_block %}
                {% get_category_list category %}
            {% endblock %}
        </div>
    <hr />
    <div>
        <ul>
            {% if user.is_authenticated %}
            <!-- Показать эти ссылки, когда пользователь вошел в систему -->
            <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
            <li><a href="{% url 'auth_logout' %}?next={% url 'rango:index' %}'">Logout</a></li>
            <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
            <li><a href="{% url 'auth_password_change' %}">Password Change</a></li>
            <li><a href="{% url 'auth_password_change_done' %}">Change Complete</a></li>
            {% else %}
            <!-- Показывать эти ссылки, когда пользователь не вошел в систему -->
            <li><a href="{% url 'registration_register' %}">Sign Up</a></li>
            <li><a href="{% url 'auth_login' %}">Login</a></li>
            {% endif %}
            <!-- Вне условных операторов всегда показывает -->
            <li><a href="{% url 'rango:about' %}">About</a></li>
            <li><a href="{% url 'rango:index' %}">Index</a></li>
        </ul>
    </div>
    </body>
</html>

tango_with_django_project/templates/rango/base.html
<!DOCTYPE html>

{% load staticfiles %}
{% load rango_template_tags %}

<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>
        Rango - {% block title_block %}How to Tango with Django!{% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
    </head>

    <body>
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">
                <a class="navbar-brand p-2" href="{% url 'rango:index' %}">Rango</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:index' %}">Home</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:about' %}">About</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:restricted' %}">Restricted</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:add_category' %}">Add Category</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_password_change' %}">Change Password</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:profile' user.username %}">Profile</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:list_profiles' %}">List Profiles</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Register Here</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'auth_login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </header>

        <div class="container-fluid">
            <div class="row">
                <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                    <div class="w-75 ml-3">
                        <input type="search" id="search-input" class="form-control ds-input" placeholder="Search..." />
                    </div>

                    <div class="sidebar-sticky" id="categories-listing">
                    {% block sidebar_block %}
                        {% get_category_list category %}
                    {% endblock %}
                    </div>
                </nav>

                <main role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">
                    {% block body_block %}{% endblock %}

                    <!-- FOOTER -->
                    <footer>
                        <p class="float-right"><a href="#">Back to top</a></p>
                        <p>&copy; 2020 Tango With Django 2 &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
                    </footer>
                </main>
            </div>
        </div>

        <!-- Bootstrap core JavaScript -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="{% static 'js/jquery-3.3.1.min.js' %}" crossorigin="anonymous"></script>
        <script src="{% static 'js/rango-jquery.js' %}" crossorigin="anonymous"></script>
        <script src="{% static 'js/rango-ajax.js'%}" crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
        <script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP"
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>
    </body>
</html>

tango_with_django_project/templates/rango/categories.html
<ul class="nav flex-column">
{% if categories %}
    {% for c in categories %}
        {% if c == current_category %}
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'rango:show_category' c.slug %}">
                    <span data-feather="archive"></span>{{ c.name }}
                </a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:show_category' c.slug %}">
                    <span data-feather="archive"></span>{{ c.name }}
                </a>
            </li>
        {% endif %}
    {% endfor %}
{% else %}
    <li class="nav-item">There are no categories present.</li>
{% endif %}
</ul>

tango_with_django_project/templates/rango/list_profiles.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    User Profiles
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">User Profiles</h1>
    </div>
</div>

<div class="container">
    <div class="row">
        {% if user_profile_list %}
        <div class="panel-body">
            <div class="list-group">
            {% for list_user in user_profile_list %}
                <div class="list-group-item">
                    <h4 class="list-group-item-heading">
                        <img src="{{ MEDIA_URL }}{{ list_user.picture }}" width="64" height="64"
                             alt="{{ list_user }}'s profile image" />
                        <a href="{% url 'rango:profile' list_user.user.username %}">{{ list_user.user.username }}</a>
                    </h4>
                </div>
            {% endfor %}
            </div>
        </div>
        {% else %}
        <p>There are no users present on Rango.</p>
        {% endif %}
    </div>
</div>
{% endblock %}

tango_with_django_project/templates/rango/page_listing.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        {% if category %}
            <h1 class="jumbotron-heading">{{ category.name }}</h1>
            <div>
                <strong id="like_count">{{ category.likes }}</strong> likes
                {% if user.is_authenticated %}
                <button id="like_btn"
                    data-categoryid="{{ category.id }}"
                    class="btn-primary btn-sm"
                    type="button">
                <span data-feather="thumbs-up"></span>
                Like Category
                </button>
                {% endif %}
            </div>
    </div>
</div>
            {% if pages %}
            <ul>
                {% for page in pages %}
                <li>
                <a href="{% url 'rango:goto' %}?page_id={{ page.id }}">{{ page.title }}</a>
                    {% if page.views > 1 %}
                        ({{ page.views }} views)
                    {% elif page.views == 1 %}
                        ({{ page.views }} view)
                    {% endif %}
                </li>
                {% endfor %}
            </ul>
            {% else %}
            <strong>No pages currently in category.</strong>
            {% endif %}
            {% if user.is_authenticated %}
            <a href="{% url 'rango:add_page' category.slug %}">Add Page</a> <br />
            {% else %}
            Что-бы добавить категорию вам необходимо войти:
            <li><a href="{% url 'auth_login' %}">Login</a></li>
            {% endif %}
        {% else %}
            The specified category does not exist.
        {% endif %}

    <!--search-->
{% if user.is_authenticated %}
    <div>
        <form class="form-inline" id="user-form" method="post" action="{% url 'rango:show_category' category.slug %}">
            {% csrf_token %}
            <div class="form-group">
                <input class="form-control" type="text" size="50" name="query" value="{{ query }}" id="query" />
            </div>
            <button class="btn btn-primary" type="submit" name="submit">Search</button>
        </form>
    </div>
    <div>
        {% if result_list %}
            <h2>Results</h2>
            <div class="list-group">
                {% for result in result_list %}
                    <div class="list-group-item">
                        <h3 class="list-group-item-heading">
                            <a href="{{ result.link }}">{{ result.title|safe|escape }}</a>
                        </h3>
                        <button class="btn btn-info btn-sm rango-page-add" type="button"
                                data-categoryid="{{ category.id }}" data-title="{{ result.title }}"
                                data-url="{{ result.link }}">Add</button>
                        <p class="list-group-item-text">{{ result.summary|safe|escape }}</p>
                    </div>

                {% endfor %}
            </div>
        {% endif %}
    </div>
{% endif %}
{% endblock %}